// import React,{ useState } from "react";
// import axios from 'axios';

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { StyleSheet, Dimensions } from "react-native";
import ResponsiveScreen from "react-native-auto-responsive-screen";
ResponsiveScreen.init(720, 1600);
const wf = Dimensions.get("screen").fontScale;
const ws = Dimensions.get("screen").scale;
const wh = Dimensions.get("screen").height;
const ww = Dimensions.get("screen").width;
// console.log(win)
const styles = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: ResponsiveScreen.fontSize(20),
    alignItems: "center",
    backgroundColor: "#f2ca30",
    // justifyContent: "center",
    height: wh,
    width: ww,
    flexDirection: "column",
    flexDirection: "row",
    // flexWrap: 'wrap',
    flex: 1,
  },
  fields: {
    fontFamily: "Roboto",
    fontSize: ResponsiveScreen.fontSize(30),
    position: "relative",
    height: wh * 4 / 100,
    width: ww * 58 / 100,
    // padding: 0,
    backgroundColor: "white",
    textAlign: "center",
    borderRadius: 50,
    // marginTop: ResponsiveScreen.normalize(-120),
    marginLeft: ww * 2.5 / 100,
    // marginRight: wp('5%'),
  },
  text: {
    fontFamily: "Roboto",
    fontSize: ResponsiveScreen.fontSize(28),
    marginLeft: ww * 3 / 100,
    marginTop: wh * 0.5 / 100,
  },
  Button: {
    // fontFamily: "Roboto",

    justifyContent: "center",
    alignItems: "center",
    // borderColor:'#fff',
    backgroundColor: "#192570",
    // color :"red",
    // Color:'blue',
    // underlayColor:'#fff',
    borderRadius: 50,
    height: wh * 5 / 100,
    width: ww * 15 / 100,
    // padding: 0,
    textAlign: "center",
    marginLeft: ww * 2 / 100,
    // Align:'left',
    // flex:0,
  },
  box: {
    fontFamily: "Roboto",
    marginTop: wh * 35 / 100,
    // height:hp("45%"),
    // width: hp("32%"),
    // marginLeft:wp("10%"),
    // marginRight:wp("10%"),
    paddingHorizontal: wh * 3 / 100,
    height: wh * 30 / 100,
    width: ww * 70 / 100,
    // backgroundColor:"red"
  },
  ButtonText: {
    fontFamily: "Roboto",
    // alignItems:'center',
    color: "white",
    // width:"100%"
    // fontSize:12,
    textAlign: "center",

    fontSize: ResponsiveScreen.fontSize(25),
    // fontSize: hp("1.4"),
    // marginTop: ws/100*200,
    // marginLeft: '25%',
    // paddingLeft: ws*700/100,
    paddingBottom: wh * 0.5 / 100,
    // backgroundColor:"red"
  },
  butbox: {
    fontFamily: "Roboto",
    justifyContent: "space-between",
    marginTop: ww * 1 / 100,
    height: wh * 10 / 100,
    width: ww * 61 / 100,
    paddingHorizontal: ww * 1 / 100,
    flexDirection: "row",
    // backgroundColor:"green",
    // flexDirection: 'column',
  },
  logo: {
    // fontFamily: "Roboto",
    // backgroundColor:"red",
    width: ww * 63 / 100,
    height: wh * 10 / 100,
    // marginRight: wp('30%'),
    marginBottom: wh * 3 / 100,
  },
});

export { styles };
const Tabletstyles = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: ResponsiveScreen.fontSize(20),
    alignItems: "center",
    backgroundColor: "#f2ca30",
    // justifyContent: "center",
    height: wh,
    width: ww,
    flexDirection: "column",
    flexDirection: "row",
    // flexWrap: 'wrap',
    flex: 1,
  },
  fields: {
    fontFamily: "Roboto",
    fontSize: ResponsiveScreen.fontSize(30),
    position: "relative",
    height: wh * 3.3 / 100,
    width: ww * 53 / 100,
    // padding: 0,
    backgroundColor: "white",
    textAlign: "center",
    borderRadius: 50,
    // marginTop: ResponsiveScreen.normalize(-120),
    marginLeft: ww * 2.5 / 100,
    // marginRight: wp('5%'),
  },
  text: {
    fontFamily: "Roboto",
    fontSize: ResponsiveScreen.fontSize(24),
    marginLeft: ww * 3 / 100,
    marginTop: -wh * 0.2 / 100,
  },
  Button: {
    // fontFamily: "Roboto",

    justifyContent: "center",
    alignItems: "center",
    // borderColor:'#fff',
    backgroundColor: "#192570",
    // color :"red",
    // Color:'blue',
    // underlayColor:'#fff',
    borderRadius: 50,
    height: wh * 4 / 100,
    width: ww * 15 / 100,
    // padding: 0,
    textAlign: "center",
    marginLeft: ww * 2 / 100,
    // Align:'left',
    // flex:0,
  },
  box: {
    fontFamily: "Roboto",
    marginTop: wh * 30 / 100,
    // height:hp("45%"),
    // width: hp("32%"),
    // marginLeft:wp("10%"),
    // marginRight:wp("10%"),
    paddingHorizontal: wh * 4 / 100,
    height: wh * 30 / 100,
    width: ww * 70 / 100,
    // backgroundColor:"red"
  },
  ButtonText: {
    fontFamily: "Roboto",
    // alignItems:'center',
    color: "white",
    // width:"100%"
    // fontSize:12,
    textAlign: "center",

    fontSize: ResponsiveScreen.fontSize(22),
    // fontSize: hp("1.4"),
    // marginTop: ws/100*200,
    // marginLeft: '25%',
    // paddingLeft: ws*700/100,
    paddingBottom: wh * 0.5 / 100,
    // backgroundColor:"red"
  },
  butbox: {
    fontFamily: "Roboto",
    justifyContent: "space-between",
    marginTop: ww * 2 / 100,
    height: wh * 10 / 100,
    width: ww * 57 / 100,
    paddingHorizontal: ww * 1 / 100,
    flexDirection: "row",
    marginLeft: -ww * 0.5 / 100
    // backgroundColor:"green",
    // flexDirection: 'column',
  },
  logo: {
    // fontFamily: "Roboto",
    // backgroundColor:"red",
    width: ww * 59 / 100,
    height: wh * 9.5 / 100,
    marginLeft: -ww * 1 / 100,
    marginBottom: wh * 1 / 100,
  },
});

export { Tabletstyles };

const styles2 = StyleSheet.create({
  logo: {
    height: hp("6%"),
    // width:50,
    width: ww / 1.7,
    // marginRight:30 ,
    // marginBottom:20 ,
    // marginTop:50 ,
    // marginLeft:30 ,
    // backgroundColor:'blue',
    resizeMode: "cover",
  },
  page: {
    fontFamily: "Roboto",

    // alignItems: 'center',
    // backgroundColor: "red",
    justifyContent: "center",
    height: wh,
    width: ww,
    flexDirection: "column",
    flexDirection: "row",
    flexWrap: "wrap",
    flex: 1,
  },
  topbox: {
    fontFamily: "Roboto",

    alignItems: "center",
    // justifyContent: 'flex-end',
    // flexDirection: 'column',

    flexDirection: "row",
    justifyContent: "space-between",


    marginTop: hp("4%"),
    height: hp("9%"),
    // width: '95%',
    width: ww,

    // padding:10,
    // backgroundColor:"green"
  },
  butbox: {
    fontFamily: "Roboto",

    borderRadius: wh * 10 / 100,
    height: wh * 85 / 100,
    width: hp("40%"),
    marginLeft: wp("-19%"),
  },
  butbox2: {
    fontFamily: "Roboto",

    borderRadius: 50,
    backgroundColor: "white",
    height: "100%",
    width: "80%",
    marginLeft: -82,
  },
  card: {
    fontFamily: "Roboto",
    fontSize: 18,
    marginTop: 20,
    marginStart: 50,
    paddingStart: 15,
    width: 280,
    height: 60,
    textAlign: "left",
    lineHeight: 50,
    borderRadius: 6,
    elevation: 3,
    backgroundColor: "#fff",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  carda: {
    fontFamily: "Roboto",
    fontSize: 18,
    marginTop: -27,
    marginStart: "20%",
    paddingStart: 1,
    width: 200,
    height: 60,
    textAlign: "left",
    lineHeight: 30,
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  cardb: {
    fontFamily: "Roboto",
    fontSize: 18,
    marginTop: -27,
    marginStart: "24%",
    paddingStart: 1,
    width: 200,
    height: 60,
    textAlign: "left",
    lineHeight: 30,
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  cardc: {
    fontFamily: "Roboto",
    fontSize: 18,
    marginTop: -27,
    marginStart: "24%",
    paddingStart: 1,
    width: 200,
    height: 60,
    textAlign: "left",
    lineHeight: 30,
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  cardd: {
    fontFamily: "Roboto",
    fontSize: 18,
    marginTop: -27,
    marginStart: "21%",
    paddingStart: 1,
    width: 200,
    height: 60,
    textAlign: "left",
    lineHeight: 30,
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  carde: {
    fontFamily: "Roboto",
    fontSize: 18,
    marginTop: -27,
    marginStart: "25%",
    paddingStart: 1,
    width: 200,
    height: 60,
    textAlign: "left",
    lineHeight: 30,
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  cardf: {
    fontFamily: "Roboto",
    fontSize: 18,
    marginTop: -27,
    marginStart: "25%",
    paddingStart: 1,
    width: 200,
    height: 60,
    textAlign: "left",
    lineHeight: 30,
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  cardg: {
    padding: 15,
    color: "gray",
    fontFamily: "Roboto",
    fontSize: 18,
    marginTop: 20,
    marginStart: 35,
    paddingStart: 11,
    width: 330,
    height: 110,
    textAlign: "left",
    lineHeight: 66,
    borderRadius: 6,
    elevation: 3,
    backgroundColor: "#fff",
    shadowOffset: { width: 3, height: 3 },
    shadowColor: "#111",
    shadowOpacity: 3,
    shadowRadius: 3,
  },

  icon1: {
    marginTop: hp("-7%"),
    marginBottom: hp("4%"),
    marginLeft: wp("16%"),
  },
  icon2: {
    marginTop: hp("-7%"),
    marginBottom: hp("7%"),
    marginLeft: wp("16%"),
  },
  icon3: {
    marginTop: hp("-7%"),
    marginBottom: hp("7%"),
    marginLeft: wp("16%"),
  },
  icon4: {
    marginTop: hp("-7%"),
    marginBottom: hp("7%"),
    marginLeft: wp("16%"),
  },
  icon5: {
    marginTop: hp("-7%"),
    marginBottom: hp("7%"),
    marginLeft: wp("16%"),
  },
  icon6: {
    marginTop: hp("-7%"),
    marginBottom: hp("7%"),
    marginLeft: wp("16%"),
  },
  icon7: {
    marginTop: hp("-7%"),
    marginBottom: hp("7%"),
    marginLeft: wp("16%"),
  },
});
const btn = StyleSheet.create({
  btn: {
    fontFamily: "Roboto",

    fontWeight: "bold",
    padding: 10,
    textAlign: "center",
    fontSize: 17,
    transform: [{ rotate: "90deg" }],
    color: "#fff",
    marginTop: -400,
    marginLeft: 420,
    // borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
    backgroundColor: "#f2c92f",
    width: 200,
    height: 50,
  },
  btn2: {
    fontFamily: "Roboto",

    fontWeight: "bold",
    padding: 10,
    textAlign: "center",
    fontSize: 15,
    transform: [{ rotate: "90deg" }],
    color: "#fff",
    marginTop: -200,
    marginLeft: 420,
    borderBottomRightRadius: 50,
    // bsorderBottomRightRadius: 20,
    backgroundColor: "#192571",
    width: 200,
    height: 50,
  },
  trapezoid1: {
    fontFamily: "Roboto",
    backgroundColor: "red",
    zIndex: 0,
    marginTop: hp("3%"),
    marginLeft: wp("3%"),
    paddingTop: 15,
    textAlign: "center",
    fontSize: 13,
    color: "#fff",
    transform: [{ rotate: "90deg" }],
    width: 250,
    height: 0,
    borderTopWidth: 55,
    borderTopColor: "#f2c92f",
    borderLeftWidth: 70,
    borderLeftColor: "transparent",
    borderRightWidth: 0,
    borderRightColor: "transparent",
    borderStyle: "solid",
  },
  trapezoid2: {
    fontFamily: "Roboto",

    zIndex: 0,
    marginTop: "15%",
    marginLeft: "143%",
    paddingTop: 15,
    paddingLeft: "1%",
    textAlign: "left",
    fontSize: 13,
    color: "#fff",
    transform: [{ rotate: "90deg" }],
    width: 250,
    height: 0,
    borderTopWidth: 55,
    borderTopColor: "#192571",
    borderLeftWidth: 0,
    borderLeftColor: "transparent",
    borderRightWidth: 70,
    borderRightColor: "transparent",
    borderStyle: "solid",
  },
  //   btna: {
  //     fontWeight: 'bold',
  //     padding:10,
  //     textAlign: 'center',
  //     fontSize:17,
  //     transform: [{ rotate: '90deg'}],
  //     color: '#fff',
  //     marginTop:-480,
  //     marginLeft: 420,
  //     // borderTopLeftRadius: 50,
  //     borderBottomLeftRadius: 50,
  // backgroundColor: '#f2c92f',
  // width: 150,
  // height: 50,
  //   },
  btnb: {
    fontFamily: "Roboto",

    paddingTop: hp("0%"),
    paddingLeft: wp("0%"),
    textAlign: "center",
    fontSize: hp("1.7%"),
    transform: [{ rotate: "90deg" }],
    color: "#000",
    marginTop: hp("-33%"),
    marginLeft: wp("125%"),
    // borderTopLeftRadius: 50,
    // borderBottomRightRadius: 50,
    backgroundColor: "#e8e4e3",
    width: wp("35%"),
    height: hp("7%"),
  },
  btnbb: {
    fontFamily: "Roboto",

    paddingTop: 15,
    paddingLeft: 5,
    textAlign: "center",
    fontSize: 14,
    transform: [{ rotate: "90deg" }],
    color: "#000",
    marginTop: "-113%",
    marginLeft: "148%",
    // borderTopLeftRadius: 50,
    // borderBottomRightRadius: 50,
    backgroundColor: "#f2c92f",
    width: 150,
    height: 55,
  },
  btnc: {
    fontFamily: "Roboto",

    fontWeight: "bold",
    padding: 10,
    textAlign: "center",
    fontSize: 17,
    transform: [{ rotate: "90deg" }],
    color: "#fff",
    marginTop: 500,
    marginLeft: 420,
    // borderTopLeftRadius: 50,
    borderBottomRightRadius: 50,
    backgroundColor: "#f2c92f",
    width: 150,
    height: 50,
  },
  btn4: {
    fontFamily: "Roboto",

    padding: 10,
    marginTop: -170,
    marginLeft: -120,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    // bsorderBottomRightRadius: 20,
    backgroundColor: "#f2c92f",
    width: 20,
    height: 170,
  },
  btn3: {
    fontFamily: "Roboto",

    padding: 10,
    marginTop: -450,
    marginLeft: -120,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    backgroundColor: "#192571",
    width: 20,
    height: 322,
  },

  trapezoida: {
    position: "absolute",
    fontFamily: "Roboto",
    // backgroundColor:'red',
    marginTop: hp("-52%"),
    marginLeft: wp("39%"),
    paddingLeft: wp("27%"),
    paddingTop: hp("0%"),
    paddingRight: wp("2%"),
    textAlign: "center",
    fontSize: hp("1.7%"),
    color: "#fff",
    transform: [{ rotate: "90deg" }],
    width: wp("20%"),
    height: hp("2%"),
    borderTopWidth: 55,
    borderTopColor: "#f2c92f",
    borderLeftWidth: 70,
    borderLeftColor: "transparent",
    borderRightWidth: 0,
    borderRightColor: "transparent",
    borderStyle: "solid",
    borderBottomStartRadius: 50,
  },
  trapezoidb: {
    fontFamily: "Roboto",

    marginTop: wp("-30%"),
    marginLeft: wp("122%"),
    paddingTop: hp("1%"),
    paddingRight: wp("10%"),
    textAlign: "center",
    fontSize: hp("1.7%"),
    color: "#fff",
    transform: [{ rotate: "90deg" }],
    width: wp("50%"),
    height: hp("2%"),
    borderTopWidth: 55,
    borderTopColor: "#f2c92f",
    borderLeftWidth: 0,
    borderLeftColor: "transparent",
    borderRightWidth: 70,
    borderRightColor: "transparent",
    borderStyle: "solid",
  },
  trapezoidc: {
    fontFamily: "Roboto",

    marginTop: "-165%",
    marginLeft: "143%",
    paddingTop: 15,
    paddingLeft: "10%",
    textAlign: "center",
    fontSize: 14,
    color: "#000",
    transform: [{ rotate: "90deg" }],
    width: 190,
    height: 0,
    borderTopWidth: 55,
    borderTopColor: "#e8e4e3",
    borderLeftWidth: 70,
    borderLeftColor: "transparent",
    borderRightWidth: 0,
    borderRightColor: "transparent",
    borderStyle: "solid",
  },
  trapezoidd: {
    fontFamily: "Roboto",

    marginTop: "-66%",
    marginLeft: "143%",
    paddingTop: 15,
    paddingRight: "20%",
    textAlign: "center",
    fontSize: 14,
    color: "#fff",
    transform: [{ rotate: "90deg" }],
    width: 190,
    height: 0,
    borderTopWidth: 55,
    borderTopColor: "#f2c92f",
    borderLeftWidth: 0,
    borderLeftColor: "transparent",
    borderRightWidth: 70,
    borderRightColor: "transparent",
    borderStyle: "solid",
  },
});
const styles3 = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: ResponsiveScreen.normalize(25),
    alignItems: "center",
    backgroundColor: "#fff",
    // justifyContent: "center",
    height: wh,
    width: ww,
    flexDirection: "column",
    // backgroundColor:"red",
    flex: 1,
    // flexDirection: "row",
    // flexWrap: 'wrap',
  },
  topbox: {
    fontFamily: "Roboto",
    alignItems: "center",
    // justifyContent: 'flex-end',
    // flexDirection: 'column',
    flexDirection: "row",
    marginTop: wh * 1 / 100,
    justifyContent: "space-between",
    // backgroundColor:'blue',
    // marginTop: "15%",
    height: wh * 12 / 100,
    // width: '95%',
    width: ww,
    // paddingTop:wh/5.9,
    // padding:'30%',
  },
  butbox: {
    fontFamily: "Roboto",
    flexDirection: "row",
    borderRadius: 20,
    height: wh * 81 / 100,
    width: ww,
    // marginLeft: wp("-19%"),
    // backgroundColor:'transparent'
    // backgroundColor:"red"
  },
  workbox: {
    fontFamily: "Roboto",
    flexDirection: "column",
    borderRadius: 20,
    height: wh * 81 / 100,
    width: ww * 85 / 100,
    // marginLeft: wp("-19%"),
    // backgroundColor:"orange"
  },
  barbox: {
    fontFamily: "Roboto",
    flexDirection: "column",
    borderRadius: 20,
    height: ResponsiveScreen.normalize(1360),
    width: ResponsiveScreen.normalize(130),
    // marginLeft: wp("-19%"),
    // backgroundColor: "green",
  },
  logo: {
    height: wh * 8 / 100,
    // width:50,
    width: ww * 55 / 100,
    // marginRight:30 ,
    // marginBottom:20 ,
    // marginTop:50 ,
    // marginLeft:30 ,
    // backgroundColor:'blue',
    resizeMode: "cover",
  },
  logo2: {
    height: wh * 6 / 100,
    // width:50,
    width: ww * 4.5 / 100,
    marginRight: ww * 6 / 100,
    // marginBottom:20 ,
    marginTop: wh * -1 / 100,
    // marginLeft:30 ,
    // backgroundColor:'blue',
    resizeMode: "cover",
  },
  barbut1: {
    fontFamily: "Roboto",
    backgroundColor: "#f2ca30",
    transform: [{ rotate: "90deg" }],
    width: wh / 5,
    height: ww / 5,
    marginTop: wh / 5.2,
    marginLeft: -(ww / 8.2),
  },
  barbut2: {
    fontFamily: "Roboto",
    backgroundColor: "#e5e5e5",
    transform: [{ rotate: "90deg" }],
    width: wh / 5,
    height: ww / 5,
    marginTop: wh / 9.1,
    marginLeft: -(ww / 8.2),
  },
  barbut3: {
    fontFamily: "Roboto",
    backgroundColor: "#f2ca30",
    transform: [{ rotate: "90deg" }],
    width: wh / 5,
    height: ww / 5,
    marginTop: wh / 9.1,
    marginLeft: -(ww / 8.2),
  },
  bartxt: {
    fontFamily: "Roboto",
    transform: [{ rotate: "90deg" }],
    width: ResponsiveScreen.normalize(250),
    height: ResponsiveScreen.normalize(50),
    marginTop: ResponsiveScreen.normalize(-150),
    marginLeft: ResponsiveScreen.normalize(-45),
    color: "#fff"
  },
  workcard: {
    // backgroundColor:"gray",
    fontFamily: "Roboto",
    width: ww * 64 / 100,
    height: wh * 6 / 100,
    marginBottom: ResponsiveScreen.normalize(49),
    borderRadius: ResponsiveScreen.normalize(18),
    flexDirection: "row",
    elevation: 10,
    backgroundColor: "#fff",
    shadowOffset: { width: 3, height: 3 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  workcard2: {
    // backgroundColor:"gray",
    fontFamily: "Roboto",
    width: ResponsiveScreen.normalize(550),

    height: ResponsiveScreen.normalize(120),
    marginBottom: ResponsiveScreen.normalize(25),
    marginLeft: ResponsiveScreen.normalize(35),
    borderRadius: ResponsiveScreen.normalize(18),
    flexDirection: "row",
    // elevation: 3,
    backgroundColor: "#fff",
    // shadowOffset: { width: 1, height: 1 },
    // shadowColor: "red",
    // shadowOpacity: 0.3,
    // shadowRadius: 1,
    zIndex: 3
  },
  txtworkcard: {
    // backgroundColor:"yellow",
    fontWeight: '500',
    fontFamily: 'sans-serif-medium',

    color: '#525151',
    // fontFamily: "Roboto",
    width: ww * 47 / 100,
    height: wh * 10 / 100,
    fontSize: ResponsiveScreen.normalize(29),
    paddingTop: wh * 1.7 / 100,
    paddingLeft: ww * 7 / 100,
    borderRadius: 20,
  },
  checkline: {
    width: ww * 3.8 / 100,
    height: wf * 15 / 100,
    backgroundColor: "#192570",
    borderRadius: 100,
    marginHorizontal: ww * 6.4 / 100,
  },
  barbut11: {
    fontFamily: "Roboto",
    // backgroundColor: "#f2ca30",
    // transform: [{ rotate: "90deg" }],
    // width: ResponsiveScreen.normalize(60),
    // height: ResponsiveScreen.normalize(20),
    marginTop: ResponsiveScreen.normalize(100),
    marginLeft: ResponsiveScreen.normalize(-9),
  },
  barbut22: {
    fontFamily: "Roboto",
    backgroundColor: "#fafafa",
    // transform: [{ rotate: "90deg" }],
    width: ResponsiveScreen.normalize(115),
    height: ResponsiveScreen.normalize(280),
    marginTop: ResponsiveScreen.normalize(-21),
    marginLeft: ResponsiveScreen.normalize(23.5),
  },
  barbut33: {
    fontFamily: "Roboto",
    marginTop: ResponsiveScreen.normalize(0),
    marginLeft: ResponsiveScreen.normalize(20),
  },
});
export { styles2, btn, styles3 };
